import { z } from "zod";

import { createClientEnv } from "@ldc/env";

const env = createClientEnv(
  {
    PUBLIC_URL_GOVERNANCE_API: z.url(),
    PUBLIC_URL_FILE_SERVICE: z.url(),
    PUBLIC_URL_AI_WORKFLOW_CONTROL_PLANE: z.url(),
    PUBLIC_WORKFLOW_VALIDATION_RULE_AGENT_API_URL: z.url(),
    PUBLIC_WORKFLOW_GOVERNANCE_AGENT_API_URL: z.url(),
    PUBLIC_WORKFLOW_PROFILE_MANAGER_API_URL: z.url(),
    PUBLIC_WORKFLOW_SUPERVISOR_AGENT_API_URL: z.url(),
    PUBLIC_INTEGRATION_HUB_API_URL: z.url(),
    PUBLIC_URL_PUSH_GATEWAY: z.url(),
  },
  {

    PUBLIC_URL_GOVERNANCE_API: import.meta.env.PUBLIC_URL_GOVERNANCE_API,
    PUBLIC_URL_FILE_SERVICE: import.meta.env.PUBLIC_URL_FILE_SERVICE,
    PUBLIC_URL_AI_WORKFLOW_CONTROL_PLANE: import.meta.env.PUBLIC_URL_AI_WORKFLOW_CONTROL_PLANE,
    PUBLIC_WORKFLOW_VALIDATION_RULE_AGENT_API_URL: import.meta.env.PUBLIC_WORKFLOW_VALIDATION_RULE_AGENT_API_URL,
    PUBLIC_WORKFLOW_GOVERNANCE_AGENT_API_URL: import.meta.env.PUBLIC_WORKFLOW_GOVERNANCE_AGENT_API_URL,
    PUBLIC_WORKFLOW_PROFILE_MANAGER_API_URL: import.meta.env.PUBLIC_WORKFLOW_PROFILE_MANAGER_API_URL,
    PUBLIC_WORKFLOW_SUPERVISOR_AGENT_API_URL: import.meta.env.PUBLIC_WORKFLOW_SUPERVISOR_AGENT_API_URL,
    PUBLIC_INTEGRATION_HUB_API_URL: import.meta.env.PUBLIC_INTEGRATION_HUB_API_URL,
    PUBLIC_URL_PUSH_GATEWAY: import.meta.env.PUBLIC_URL_PUSH_GATEWAY,
  },
);

export { env };

