import { z } from "zod";

import { createClientEnv } from "@ldc/env";

const env = createClientEnv(
  {
    PUBLIC_GOVERNANCE_API_URL: z.url(),
    PUBLIC_FILE_SERVICE_URL: z.url(),
    PUBLIC_WORKFLOW_API_URL: z.url(),
    PUBLIC_WORKFLOW_VALIDATION_RULE_AGENT_API_URL: z.url(),
    PUBLIC_WORKFLOW_GOVERNANCE_AGENT_API_URL: z.url(),
    PUBLIC_WORKFLOW_PROFILE_MANAGER_API_URL: z.url(),
    PUBLIC_WORKFLOW_SUPERVISOR_AGENT_API_URL: z.url(),
    PUBLIC_INTEGRATION_HUB_API_URL: z.url(),
    PUBLIC_PUSH_GATEWAY_URL: z.url(),
  },
  {
    PUBLIC_GOVERNANCE_API_URL: import.meta.env.PUBLIC_GOVERNANCE_API_URL,
    PUBLIC_FILE_SERVICE_URL: import.meta.env.PUBLIC_FILE_SERVICE_URL,
    PUBLIC_WORKFLOW_API_URL: import.meta.env.PUBLIC_WORKFLOW_API_URL,
    PUBLIC_WORKFLOW_VALIDATION_RULE_AGENT_API_URL: import.meta.env.PUBLIC_WORKFLOW_VALIDATION_RULE_AGENT_API_URL,
    PUBLIC_WORKFLOW_GOVERNANCE_AGENT_API_URL: import.meta.env.PUBLIC_WORKFLOW_GOVERNANCE_AGENT_API_URL,
    PUBLIC_WORKFLOW_PROFILE_MANAGER_API_URL: import.meta.env.PUBLIC_WORKFLOW_PROFILE_MANAGER_API_URL,
    PUBLIC_WORKFLOW_SUPERVISOR_AGENT_API_URL: import.meta.env.PUBLIC_WORKFLOW_SUPERVISOR_AGENT_API_URL,
    PUBLIC_INTEGRATION_HUB_API_URL: import.meta.env.PUBLIC_INTEGRATION_HUB_API_URL,
    PUBLIC_PUSH_GATEWAY_URL: import.meta.env.PUBLIC_PUSH_GATEWAY_URL,
  },
);

export { env };
